default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: iris_user
  password: iris_pass
  host: iris-mysql
  port: 3306

development:
  <<: *default
  database: iris_db

test:
  <<: *default
  database: iris_systems_rec_task_test

production:
  <<: *default
  database: iris_systems_rec_task_production
  username: iris_systems_rec_task
  password: "<%= ENV['IRIS_SYSTEMS_REC_TASK_DATABASE_PASSWORD'] %>"