limit_req_zone $binary_remote_addr zone=app_limit:10m rate=5r/s;

upstream rails_app {
    server iris-rails-1:3000;
    server iris-rails-2:3000;
    server iris-rails-3:3000;
}

server {
    listen 80;

    location / {
        limit_req zone=app_limit burst=2 nodelay;

        proxy_pass http://rails_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
